version: '3.7'
services:
  client:
    build:
      context: .
      dockerfile: ./.docker/client.dockerfile
    ports:
      - "8080:8080"
    networks:
      - mevn-network
    depends_on: 
      - server
    volumes: 
       - ./client/node_modules:/var/www/node_modules
  server:
    build:
      context: .
      dockerfile: ./.docker/server.dockerfile
    ports:
      - "3333:3333"
    networks:
      - mevn-network
    depends_on: 
      - mongodb
    volumes: 
       - ./server/node_modules:/var/www/node_modules
  mongodb:
    image: mongo
    networks:
      - mevn-network
networks:
  mevn-network:
    driver: bridge